"""
Test script for validating collected StandX data.
Runs validation tests on Parquet files generated by data_collector.py.
"""

import json
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import List, Tuple

import pandas as pd


class TestResult:
    """Container for test results."""

    def __init__(self, name: str):
        self.name = name
        self.passed = 0
        self.failed = 0
        self.errors: List[str] = []

    def add_pass(self):
        self.passed += 1

    def add_fail(self, error: str):
        self.failed += 1
        self.errors.append(error)

    @property
    def total(self):
        return self.passed + self.failed

    @property
    def success(self):
        return self.failed == 0


def load_config(config_path: str = "config.json"):
    """Load configuration file. Returns (config_dict, config_file_path)."""
    config_file = Path(config_path)
    if not config_file.exists():
        # Search one level up (e.g., running from data_collector/ subfolder)
        parent_config = Path(__file__).resolve().parent.parent / config_file.name
        if parent_config.exists():
            config_file = parent_config
    config_file = config_file.resolve()
    with open(config_file, 'r') as f:
        return json.load(f), config_file


def find_parquet_files(data_dir: Path) -> Tuple[List[Path], List[Path]]:
    """Find orderbook and trade Parquet files."""
    orderbook_files = list(data_dir.glob("orderbook_*.parquet"))
    trades_files = list(data_dir.glob("trades_*.parquet"))
    return orderbook_files, trades_files


def test_orderbook_ordering(df: pd.DataFrame) -> TestResult:
    """Test that orderbook bids are descending and asks are ascending."""
    result = TestResult("Orderbook Ordering")

    for idx, row in df.iterrows():
        bid_prices = row['bid_prices']
        ask_prices = row['ask_prices']

        # Filter out None values
        bid_prices = [p for p in bid_prices if p is not None]
        ask_prices = [p for p in ask_prices if p is not None]

        # Test bids descending
        for i in range(len(bid_prices) - 1):
            if bid_prices[i] < bid_prices[i + 1]:
                result.add_fail(
                    f"Row {idx}: Bids not descending at level {i}: "
                    f"{bid_prices[i]} < {bid_prices[i+1]}"
                )
            else:
                result.add_pass()

        # Test asks ascending
        for i in range(len(ask_prices) - 1):
            if ask_prices[i] > ask_prices[i + 1]:
                result.add_fail(
                    f"Row {idx}: Asks not ascending at level {i}: "
                    f"{ask_prices[i]} > {ask_prices[i+1]}"
                )
            else:
                result.add_pass()

    return result


def test_no_crossed_book(df: pd.DataFrame) -> TestResult:
    """
    Test that best ask is >= best bid (no crossed book).
    Note: best_bid == best_ask is a 'locked market' which is valid.
    """
    result = TestResult("No Crossed Book")

    for idx, row in df.iterrows():
        best_bid = row['best_bid']
        best_ask = row['best_ask']

        if best_bid is None or best_ask is None:
            continue

        if best_bid > best_ask:
            result.add_fail(
                f"Row {idx}: Crossed book - best_bid={best_bid} > best_ask={best_ask}"
            )
        else:
            result.add_pass()

    return result


def test_positive_quantities(df: pd.DataFrame) -> TestResult:
    """Test that all quantities are positive."""
    result = TestResult("Positive Quantities")

    for idx, row in df.iterrows():
        bid_qtys = row['bid_quantities']
        ask_qtys = row['ask_quantities']

        for i, qty in enumerate(bid_qtys):
            if qty is not None:
                if qty <= 0:
                    result.add_fail(f"Row {idx}: Bid qty at level {i} is <= 0: {qty}")
                else:
                    result.add_pass()

        for i, qty in enumerate(ask_qtys):
            if qty is not None:
                if qty <= 0:
                    result.add_fail(f"Row {idx}: Ask qty at level {i} is <= 0: {qty}")
                else:
                    result.add_pass()

    return result


def test_level_count(df: pd.DataFrame, expected_levels: int) -> TestResult:
    """Test that we have the expected number of levels."""
    result = TestResult(f"Level Count (expected {expected_levels})")

    for idx, row in df.iterrows():
        bid_count = len([p for p in row['bid_prices'] if p is not None])
        ask_count = len([p for p in row['ask_prices'] if p is not None])

        if bid_count < expected_levels:
            result.add_fail(f"Row {idx}: Only {bid_count} bid levels (expected {expected_levels})")
        else:
            result.add_pass()

        if ask_count < expected_levels:
            result.add_fail(f"Row {idx}: Only {ask_count} ask levels (expected {expected_levels})")
        else:
            result.add_pass()

    return result


def test_spread_validity(df: pd.DataFrame) -> TestResult:
    """
    Test that spread is calculated correctly and non-negative.
    Note: spread = 0 is valid (locked market where bid == ask).
    """
    result = TestResult("Spread Validity")

    for idx, row in df.iterrows():
        best_bid = row['best_bid']
        best_ask = row['best_ask']
        spread = row['spread']

        if best_bid is None or best_ask is None:
            continue

        expected_spread = best_ask - best_bid

        if spread is None:
            result.add_fail(f"Row {idx}: Spread is None but should be {expected_spread}")
        elif abs(spread - expected_spread) > 0.0001:
            result.add_fail(
                f"Row {idx}: Spread mismatch - got {spread}, expected {expected_spread}"
            )
        elif spread < 0:
            result.add_fail(f"Row {idx}: Spread is negative: {spread}")
        else:
            result.add_pass()

    return result


def test_trade_fields(df: pd.DataFrame) -> TestResult:
    """Test that all required trade fields are present and valid."""
    result = TestResult("Trade Fields")

    required_fields = ['timestamp', 'symbol', 'price', 'quantity', 'side', 'is_buyer_taker']

    for field in required_fields:
        if field not in df.columns:
            result.add_fail(f"Missing required field: {field}")
        else:
            result.add_pass()

    for idx, row in df.iterrows():
        # Check price is positive
        if row['price'] <= 0:
            result.add_fail(f"Row {idx}: Price is not positive: {row['price']}")
        else:
            result.add_pass()

        # Check quantity is positive
        if row['quantity'] <= 0:
            result.add_fail(f"Row {idx}: Quantity is not positive: {row['quantity']}")
        else:
            result.add_pass()

        # Check side is valid
        if row['side'] not in ['BUY', 'SELL']:
            result.add_fail(f"Row {idx}: Invalid side: {row['side']}")
        else:
            result.add_pass()

        # Check side matches is_buyer_taker
        expected_side = 'BUY' if row['is_buyer_taker'] else 'SELL'
        if row['side'] != expected_side:
            result.add_fail(
                f"Row {idx}: Side mismatch - side={row['side']}, "
                f"is_buyer_taker={row['is_buyer_taker']}"
            )
        else:
            result.add_pass()

    return result


def test_timestamps_non_decreasing(df: pd.DataFrame) -> TestResult:
    """
    Test that timestamps are non-decreasing (monotonically increasing or equal).
    Note: Multiple trades/orderbooks can have the same timestamp (batch updates).
    """
    result = TestResult("Timestamps Non-Decreasing")

    if len(df) < 2:
        result.add_pass()
        return result

    timestamps = pd.to_datetime(df['timestamp'])

    for i in range(1, len(timestamps)):
        if timestamps.iloc[i] < timestamps.iloc[i - 1]:
            result.add_fail(
                f"Timestamp decreased at index {i}: "
                f"{timestamps.iloc[i]} < {timestamps.iloc[i-1]}"
            )
        else:
            result.add_pass()

    return result


def test_trade_uniqueness(df: pd.DataFrame) -> TestResult:
    """
    Test that there are no exact duplicate trades.
    Same timestamp with different price/qty is valid (batch fills).
    Exact duplicates (same timestamp, price, qty, side) should be removed.
    """
    result = TestResult("No Duplicate Trades")

    if len(df) < 2:
        result.add_pass()
        return result

    # Check for exact duplicates across the entire dataframe
    duplicates = df.duplicated(subset=['timestamp', 'price', 'quantity', 'side'], keep=False)
    num_duplicates = duplicates.sum()

    if num_duplicates > 0:
        result.add_fail(f"Found {num_duplicates} exact duplicate trades")
    else:
        result.add_pass()

    # Also verify trades with same timestamp have different values (valid batch fills)
    grouped = df.groupby('timestamp')
    for ts, group in grouped:
        if len(group) > 1:
            result.add_pass()  # Multiple trades at same timestamp is valid

    return result


def test_parquet_readable(file_path: Path) -> TestResult:
    """Test that Parquet file can be read correctly."""
    result = TestResult(f"Parquet Readable: {file_path.name}")

    try:
        df = pd.read_parquet(file_path)
        result.add_pass()

        if len(df) == 0:
            result.add_fail("File is empty")
        else:
            result.add_pass()

    except Exception as e:
        result.add_fail(f"Error reading file: {e}")

    return result


def print_result(result: TestResult, verbose: bool = False):
    """Print test result."""
    status = "PASS" if result.success else "FAIL"
    print(f"  [{status}] {result.name}: {result.passed}/{result.total} passed")

    if verbose and result.errors:
        for error in result.errors[:5]:  # Show first 5 errors
            print(f"       - {error}")
        if len(result.errors) > 5:
            print(f"       ... and {len(result.errors) - 5} more errors")


def run_tests(data_dir: Path, expected_levels: int, verbose: bool = False) -> bool:
    """Run all validation tests."""
    print("\n" + "=" * 60)
    print("StandX Data Collector - Validation Tests")
    print("=" * 60)
    print(f"Data directory: {data_dir}")
    print(f"Expected orderbook levels: {expected_levels}")
    print()

    orderbook_files, trades_files = find_parquet_files(data_dir)

    if not orderbook_files and not trades_files:
        print("ERROR: No Parquet files found in data directory!")
        print("Run data_collector.py first to collect some data.")
        return False

    all_passed = True
    results: List[TestResult] = []

    # Test orderbook files
    if orderbook_files:
        print(f"Found {len(orderbook_files)} orderbook file(s)")
        for file_path in orderbook_files:
            print(f"\nTesting: {file_path.name}")

            # Test file is readable
            readable_result = test_parquet_readable(file_path)
            results.append(readable_result)
            print_result(readable_result, verbose)

            if not readable_result.success:
                continue

            df = pd.read_parquet(file_path)
            print(f"  Records: {len(df)}")

            # Run orderbook tests
            ordering_result = test_orderbook_ordering(df)
            results.append(ordering_result)
            print_result(ordering_result, verbose)

            crossed_result = test_no_crossed_book(df)
            results.append(crossed_result)
            print_result(crossed_result, verbose)

            qty_result = test_positive_quantities(df)
            results.append(qty_result)
            print_result(qty_result, verbose)

            level_result = test_level_count(df, expected_levels)
            results.append(level_result)
            print_result(level_result, verbose)

            spread_result = test_spread_validity(df)
            results.append(spread_result)
            print_result(spread_result, verbose)

            ts_result = test_timestamps_non_decreasing(df)
            results.append(ts_result)
            print_result(ts_result, verbose)
    else:
        print("No orderbook files found")

    # Test trades files
    if trades_files:
        print(f"\nFound {len(trades_files)} trades file(s)")
        for file_path in trades_files:
            print(f"\nTesting: {file_path.name}")

            # Test file is readable
            readable_result = test_parquet_readable(file_path)
            results.append(readable_result)
            print_result(readable_result, verbose)

            if not readable_result.success:
                continue

            df = pd.read_parquet(file_path)
            print(f"  Records: {len(df)}")

            # Run trade tests
            fields_result = test_trade_fields(df)
            results.append(fields_result)
            print_result(fields_result, verbose)

            ts_result = test_timestamps_non_decreasing(df)
            results.append(ts_result)
            print_result(ts_result, verbose)

            uniqueness_result = test_trade_uniqueness(df)
            results.append(uniqueness_result)
            print_result(uniqueness_result, verbose)
    else:
        print("\nNo trades files found")

    # Summary
    print("\n" + "=" * 60)
    print("TEST SUMMARY")
    print("=" * 60)

    total_passed = sum(r.passed for r in results)
    total_failed = sum(r.failed for r in results)
    total_tests = total_passed + total_failed

    passed_suites = sum(1 for r in results if r.success)
    failed_suites = sum(1 for r in results if not r.success)

    print(f"Test suites: {passed_suites} passed, {failed_suites} failed")
    print(f"Individual checks: {total_passed}/{total_tests} passed")

    all_passed = failed_suites == 0

    if all_passed:
        print("\nAll tests PASSED!")
    else:
        print("\nSome tests FAILED. Run with --verbose for details.")

    return all_passed


def main():
    """Main entry point."""
    import argparse

    parser = argparse.ArgumentParser(description="Test StandX data collector output")
    parser.add_argument(
        "--config", "-c",
        default="config.json",
        help="Path to config.json file"
    )
    parser.add_argument(
        "--data-dir", "-d",
        help="Data directory (overrides config)"
    )
    parser.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Show detailed error messages"
    )

    args = parser.parse_args()

    # Load config
    try:
        config, config_file = load_config(args.config)
    except FileNotFoundError:
        print(f"Error: Config file not found: {args.config}")
        sys.exit(1)

    if args.data_dir:
        data_dir = Path(args.data_dir)
    else:
        # Resolve output_dir relative to the config file's directory
        data_dir = (config_file.parent / config.get("output_dir", "./data")).resolve()
    expected_levels = config.get("orderbook_levels", 20)

    if not data_dir.exists():
        print(f"Error: Data directory does not exist: {data_dir}")
        print("Run data_collector.py first to collect some data.")
        sys.exit(1)

    success = run_tests(data_dir, expected_levels, args.verbose)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
